---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - "App Store"
  - Contacts
  - FaceTime
  - Freeform
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - "System Settings"
  - TV
dockitems_persist:
  - name: "Finder"
    path: "/Applications/Finder.app/"
    pos: 1
  - name: "Launchpad"
    path: "/Applications/Arc.app/"
    pos: 2
  - name: "Arc"
    path: "/Applications/Arc.app/"
    pos: 3
  - name: "Calendar"
    path: "/Applications/Calendar.app/"
    pos: 4
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 5
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/NuroDev/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .aliases
  - .fet
  - .functions
  - .gitconfig
  - .gitignore
  - .nirc
  - .osx
  - .zshrc

homebrew_installed_packages:
  - ansible # Automate deployment, configuration, and upgrading
  - ansible-lint # Linting for Ansible.
  - bat # A cat(1) clone with wings.
  - croc # Securely send things from one computer to another
  - duf # Disk Usage/Free Utility.
  - dust # A more intuitive version of du in rust
  - ffmpeg # Play, record, convert, and stream audio and video.
  - gping # Ping, but with a graph.
  - htop # Improved top (interactive process viewer).
  - httpstat # curl statistics made simple.
  - imagemagick # Tools and libraries to manipulate images
  - iperf # Network bandwidth measurement tool.
  - jq # Lightweight and flexible command-line JSON processor.
  - lporg # Organize Your macOS Launchpad Apps
  - lsd # The next gen ls command.
  - m-cli # Swiss Army Knife for macOS.
  - mas # Mac App Store command-line interface.
  - nano # Free (GNU) replacement for the Pico text editor.
  - nmap # Network exploration tool and security scanner.
  - nushell # A new type of shell.
  - openssl # Cryptography and SSL/TLS Toolkit
  - sl # 🚂
  - ssh-copy-id # Add a public key to a remote machine's authorized_keys file.
  - starship # The minimal, blazing-fast, and infinitely customizable prompt for any shell!
  - trash # CLI tool that moves files or folders to the trash.
  - tree # Display directories as trees (with optional color/HTML output).
  - wget # Internet file retriever.
  - zsh # UNIX shell

homebrew_taps:
  - blacktop/tap # Required for `lporg`

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password # Password manager
  - arc # Chromium based browser
  - brooklyn # Screen saver based on animations presented during Apple Special Event Brooklyn
  - handbrake # Open-source video transcoder
  - hot # Menu bar application that displays the CPU speed limit due to thermal issues
  - iterm2 # Terminal emulator as alternative to Apple's Terminal app
  - orbstack # Replacement for Docker Desktop
  - rocket # Emoji picker optimised for blind people
  - utm # Virtual machines UI using QEMU
  - visual-studio-code # Open-source code editor

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
# mas_email: ""
# mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
gem_packages: []
npm_packages: []
pip_packages: []

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
