---
- name: Clone git repositories.
  loop: "{{ git_repos }}"
  ansible.builtin.git:
    clone: true
    dest: "{{ item.path }}"
    repo: "{{ item.url }}"
    update: "{{ item.update | default(yes) }}"
    version: "{{ item.version | default('main') }}"
