---
- name: Clone git repositories.
  loop: "{{ git_repos }}"
  ansible.builtin.git:
    clone: true
    dest: "{{ item.path }}"
    repo: "{{ item.url }}"
    update: "{{ item.update | default(true) | bool }}"
    version: "{{ item.branch | default('main') }}"
