---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false

- name: Configure Hostname
  when: configure_hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: "macos"

- name: Add symbolic links
  loop: "{{ symlinks }}"
  when: configure_symlinks
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(false) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    src: "{{ item.src }}"
    state: link
